name: CI

on: pull_request

jobs:
  repoman:
    runs-on: ubuntu-latest
    container: gentoo/stage3:amd64-systemd
    steps:
    - uses: actions/checkout@v2
    - name: install portage
      run: emerge-webrsync
    - name: install repoman
      run: emerge app-portage/repoman
    - name: repoman checks
      run: repoman -d full
